# TWayFoil.jl

🎯主要功能：PNG图像 ⇌ 任意文件

- ✨PNG加壳：使用ARGB PNG**图像**【加密】**任意文件**
- 🌟PNG解壳：【还原】ARGB PNG**图像**为**普通文件**

## 建立模块上下文

In [83]:
#= %only-compiled # * 主模块：TWayFoil
module TWayFoil
%only-compiled =#

## PNG API

In [84]:
using PNGFiles
using ColorTypes

In [85]:
# %ignore-cell
path = "./../test/ArcjOneHundredThirtySevenThousandAndFourHundredFortyTwo.test.png"

test = PNGFiles.load(path)
@show typeof(test) size(test)
test

typeof(test) = Matrix{GrayA{N0f8}}
size(test) = (261, 268)


261×268 Array{GrayA{N0f8},2} with eltype GrayA{N0f8}:
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)  …  GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)  …  GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)  …  GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0)     GrayA{N0f8}(0.992,1.0)
 GrayA{N0f8}(0.992,1.0)  GrayA{N0f8}(0.992,1.0

In [86]:
# %ignore-cell
@show test[1:1]

test[1:1] = GrayA{N0f8}[GrayA{N0f8}(0.992,1.0)]


In [87]:
# %ignore-cell
test[:, 1]

In [88]:
# %ignore-cell
test[:, size(test,2)÷2]

In [89]:
# %ignore-cell
RGBA |> methods

# 9 methods for type constructor:
 [1] RGBA(r::T, g::T, b::T, alpha::T) where T<:Integer
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:531
 [2] RGBA(r::T, g::T, b::T) where T<:Integer
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:531
 [3] RGBA(c::RGB, alpha::Real)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:532
 [4] RGBA(c::Color, alpha::Real)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:543
 [5] RGBA(c::RGB)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:532
 [6] RGBA()
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:544
 [7] RGBA(r, g, b)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:533
 [8] RGBA(x)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:545
 [9] RGBA(r, g, b, alpha::Real)
     @ C:\Users\Administrator\.julia\packages\ColorTypes\1dGw6\src\types.jl:538

In [90]:
# %ignore-cell
ColorTypes |> names .|> println;

ABGR
ADIN99
ADIN99d
ADIN99o
AGray
AGray32
AHSI
AHSL
AHSV
ALCHab
ALCHuv
ALMS
ALab
ALuv
ARGB
ARGB32
AXYZ
AYCbCr
AYIQ
AbstractAGray
AbstractARGB
AbstractGray
AbstractGrayA
AbstractRGB
AbstractRGBA
AlphaColor
AxyY
BGR
BGRA
Color
Color3
ColorAlpha
ColorTypes
Colorant
ColorantNormed
DIN99
DIN99A
DIN99d
DIN99dA
DIN99o
DIN99oA
Fractional
Gray
Gray24
GrayA
HSB
HSI
HSIA
HSL
HSLA
HSV
HSVA
LCHab
LCHabA
LCHuv
LCHuvA
LMS
LMSA
Lab
LabA
Luv
LuvA
RGB
RGB24
RGBA
RGBX
Transparent3
TransparentColor
TransparentGray
TransparentRGB
XRGB
XYZ
XYZA
YCbCr
YCbCrA
YIQ
YIQA
alpha
alphacolor
base_color_type
base_colorant_type
blue
ccolor
chroma
color
color_type
coloralpha
comp1
comp2
comp3
comp4
comp5
gamutmax
gamutmin
gray
green
hue
mapc
mapreducec
parametric_colorant
red
reducec
xyY
xyYA


In [91]:
# %ignore-cell
@show ARGB(test[1,1]) HSV(test[1,1])

ARGB(test[1, 1]) = ARGB{N0f8}(0.992,0.992,0.992,1.0)
HSV(test[1, 1]) = HSV{Float32}(0.0f0,0.0f0,0.99215686f0)


In [92]:
# %ignore-cell
(color -> 0.1 < HSV(color).v < 0.9).(test)

261×268 BitMatrix:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  1     0 

In [93]:
# %ignore-cell
let p = ARGB(test[0x80,0x40])
    @show p.r p.g p.b p.alpha
    @show UInt8(round(p.r * 0xff)) UInt8(round(p.g * 0xff)) UInt8(round(p.b * 0xff)) UInt8(round(p.alpha * 0xff))
    p
end

p.r = 0.984N0f8
p.g = 0.984N0f8
p.b = 0.984N0f8
p.alpha = 1.0N0f8
UInt8(round(p.r * 0xff)) = 0xfb
UInt8(round(p.g * 0xff)) = 0xfb
UInt8(round(p.b * 0xff)) = 0xfb
UInt8(round(p.alpha * 0xff)) = 0xff


## 32位ARGB转换⇒PNG转文件

In [94]:
# %ignore-cell # !【2024-01-22 00:10:15】实际使用的库代码并不需要这样的「HEX」编码
HEX(argb::ARGB)::UInt32 = (
    + (UInt32(round(argb.alpha * 0xff)) << 24)
    + (UInt32(round(argb.r     * 0xff)) << 16)
    + (UInt32(round(argb.g     * 0xff)) << 8)
    + (UInt32(round(argb.b     * 0xff)))
)

HEX(color)::UInt32 = HEX(ARGB(color))

HEX2ARGB(hex::UInt32)::ARGB = ARGB(
    ((hex >> 16) & 0xff) / 0xff,
    ((hex >> 8 ) & 0xff) / 0xff,
    ((hex      ) & 0xff) / 0xff,
    ((hex >> 24) & 0xff) / 0xff,
)

let p = test[0x80, 0x40]
    @show p HEX(p)
    p2 = HSV(0.5, 0.5, 0.5)
    p3 = HEX2ARGB(0x8066ccff)
    @show HEX(p2) HEX(p3) p3
end

p = GrayA{N0f8}(0.984,1.0)
HEX(p) = 0xfffbfbfb
HEX(p2) = 0xff804040
HEX(p3) = 0x8066ccff
p3 = ARGB{Float64}(0.4,0.8,1.0,0.5019607843137255)


In [95]:
# %ignore-cell
pixels = [
    pixel
    for row in eachcol(test)
    for pixel in row
]

┌ Warning: Last 53564 swatches (of 69948-element Array) are truncated.
└ @ Colors C:\Users\Administrator\.julia\packages\Colors\mIuXl\src\display.jl:51


In [96]:
# %ignore-cell
hexes = HEX.(pixels)

69948-element Vector{UInt32}:
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
          ⋮
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd
 0xfffdfdfd

In [97]:
# %ignore-cell # !【2024-01-22 00:10:45】实际库文件中实装的是另一个版本
function png2raw_pure(png)
    local raw8 = UInt8[]
    local argb::ARGB
    for row in eachcol(png)
        for pixel in row
            argb = ARGB(pixel)
            push!(raw8,
                UInt8(round(argb.alpha * 0xff)),
                UInt8(round(argb.r     * 0xff)),
                UInt8(round(argb.g     * 0xff)),
                UInt8(round(argb.b     * 0xff)),
            )
        end
    end
    raw8
end

let raw = png2raw_pure(test)
    @show write("png2raw(test).test.txt", raw)
    raw
end

write("png2raw(test).test.txt", raw) = 279792


279792-element Vector{UInt8}:
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
    ⋮
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd

升级版——自动识别尾部「不足四字节」的部分

- 这些可能是其它文件转换成的PNG

In [98]:
"""
识别并裁剪PNG「自动补足」的字节
- 📌按照【固定添加】的末尾字节，计算「先前转换成ARGB PNG时，因『4字节需要』而【多新增】的字节数」
    - 此处仅需一个字节，并且这个字节固定在最后
    - 所有可能取值为：0x01~0x04
        - 下限/0x01：添加该字节后正好，只需删掉本身（已经算入在pop!里边了）
        - 上限/0x04：添加该字节后冗余3个字节，该字节和其它仨（一般为空）组成了新ARGB像素
    - 其它范围外取值：返回自身
"""
function strip_raw_by_last_pixel!(raw8::Vector{UInt8})
    # * 利用【固定添加】获取末尾「新增数」
    local num_surplussed_bytes = raw8[end]
    # 使用「新增数+1」进行【截取】
    if num_surplussed_bytes in 0x01:0x04
        for _ in 1:num_surplussed_bytes
            pop!(raw8)
        end
    end
    # 返回
    raw8
end

"适应其它类型，如生成器"
strip_raw_by_last_pixel(raw8) = raw8 |> collect |> strip_raw_by_last_pixel!

# %ignore-begin # * 测试
let 
    s1 = @show strip_raw_by_last_pixel(UInt8(c) for c in "12345") # ! 「UInt('5') == 0x35」过大，不做处理
    s2 = @show strip_raw_by_last_pixel(UInt8(c) for c in "12345\x01") # 后续这俩正常操作
    s3 = @show strip_raw_by_last_pixel(UInt8(c) for c in "12345\x00\x00\x00\x04") # 后续这俩正常操作
    @assert s1 == s2 == s3
end
# %ignore-end

#= %only-compiled
export png2raw # * 导出核心函数
%only-compiled =#

"""
    png2raw(目标类型or目标路径, 待转换对象)
PNG⇒文件
- 📌将PNG按照「先行后列」的方式扫描，并返回字节串
- 📌核心流程：图片路径⇒像素矩阵⇒字节串⇒文件
"""
function png2raw end

# 图片⇒矩阵
png2raw(from::AbstractString) = png2raw(
    replace(from, r".png$" => ""),
    from
)
png2raw(destination, from::AbstractString) = png2raw(
    destination,
    PNGFiles.load(from) # 加载出一个矩阵
)

# 矩阵⇒向量
function png2raw(png::Matrix)
    # * 开始计算、存储并返回ARGB序列 * #
    local raw8 = UInt8[]
    local argb::ARGB

    # * 先注入长度
    for row in eachcol(png)
        for pixel in row
            # 动态获取像素
            argb = ARGB(pixel)
            # 一个像素转换成四个字节
            push!(raw8,
                UInt8(round(argb.alpha * 0xff)),
                UInt8(round(argb.r     * 0xff)),
                UInt8(round(argb.g     * 0xff)),
                UInt8(round(argb.b     * 0xff)),
            )
        end
    end
    
    # * 后进行截取
    return strip_raw_by_last_pixel!(raw8)
end
png2raw(destination, png::Matrix) = png2raw(destination, #= 矩阵⇒向量 =#png2raw(png))

# 向量⇒文件|向量
png2raw(::Type{<:Vector}, raw::Vector) = raw # * 向量类型⇒自身
png2raw(destination::AbstractString, raw::Vector) = write(
    destination,
    raw
)

# %ignore-begin
let raw = png2raw(test)
    # 尝试把读取后的测试图片进行转换
    @time @show write("png2raw(test).test.txt", raw)
    raw
end
# %ignore-end

strip_raw_by_last_pixel((UInt8(c) for c = "12345")) = UInt8[0x31, 0x32, 0x33, 0x34, 0x35]
strip_raw_by_last_pixel((UInt8(c) for c = "12345\x01")) = UInt8[0x31, 0x32, 0x33, 0x34, 0x35]
strip_raw_by_last_pixel((UInt8(c) for c = "12345\0\0\0\x04")) = UInt8[0x31, 0x32, 0x33, 0x34, 0x35]
write("png2raw(test).test.txt", raw) = 279792
  0.001215 seconds (46 allocations: 1.609 KiB)


279792-element Vector{UInt8}:
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
    ⋮
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd
 0xff
 0xfd
 0xfd
 0xfd

## 文件⇒PNG

In [99]:
# %ignore-cell
file = "./../Manifest.toml"
file_raw = read(file)

6537-element Vector{UInt8}:
 0x23
 0x20
 0x54
 0x68
 0x69
 0x73
 0x20
 0x66
 0x69
 0x6c
 0x65
 0x20
 0x69
    ⋮
 0x20
 0x22
 0x31
 0x2e
 0x36
 0x2e
 0x34
 0x30
 0x2b
 0x30
 0x22
 0x0a

In [100]:
# 使用N0f8转换
using ColorTypes: reinterpret, N0f8

字节串⇒像素序列

In [101]:
"""
计算「自动补足」过程中需要补足的「空白字节」个数
- 📌除了最后一个表示「转换时补足的字节个数」的字节，其它都为「空白字节」
    - ⚠️其数目可能为零
"""
n_complement_blank_bytes(len::Integer) = 3 - (len & 0b11)

"""
更通用地计算「自动补足n字节单元」所需的「空白字节数」
"""
n_complement_blank_bytes(len::Integer, n::Unsigned) = (n - 1) - (len & 0b11)

# %ignore-begin
let
    @assert n_complement_blank_bytes.([
        12
        13
        14
        15
    ]) == [
        3
        2
        1
        0
    ]
end
# %ignore-end

"""
自动补足
- 📌按照`png2raw`的思路，对字节串进行「四位补足」
    - 一定会【补足】一个像素，故字节值必定大于零
"""
function complete_4_bytes!(raw::AbstractVector{UInt8})
    # 根据个数补足「空白字符」
    local n_blank_bytes::UInt8 = n_complement_blank_bytes(length(raw))
    for _ in 1:n_blank_bytes
        push!(raw, UInt8(0))
    end

    # 添加 | 这时候要算上其自身
    push!(raw, UInt8(n_blank_bytes + 1))

    # 返回空 | 断言`@assert (length(v) & 0b11) == 0b0 raw`一定成立
    nothing
end

# %ignore-begin
let v = UInt8[1,2,3,4,5]
    complete_4_bytes!(v)
    @assert (length(v) & 0b11) == 0b0 raw
    complete_4_bytes!(v)
    @assert (length(v) & 0b11) == 0b0 raw
    push!(v, 1, 2)
    complete_4_bytes!(v)
    @assert (length(v) & 0b11) == 0b0 raw
    push!(v, 1, 2, 3)
    complete_4_bytes!(v)
    @assert (length(v) & 0b11) == 0b0 raw
    @show v
end
# %ignore-end

"""
字节串⇒像素序列
- 📌首先进行「自动补足」（破坏性操作！）
- 然后「四位转换」
"""
function raw2argb!(raw::AbstractVector{UInt8})::Vector{ARGB{N0f8}}
    # 自动补足
    complete_4_bytes!(raw)
    # 四个一批转换
    local result = ARGB{N0f8}[] # !【2024-01-21 23:54:57】后续必须得是`Matrix{ARGB{N0f8}}`类型才能被存储
    for i in 0:((length(raw) >> 2 #= 像素个数 =#) - 1)
        push!(result, ARGB{N0f8}(
            reinterpret(N0f8, raw[(i << 2) + 2]), # R
            reinterpret(N0f8, raw[(i << 2) + 3]), # G
            reinterpret(N0f8, raw[(i << 2) + 4]), # B
            reinterpret(N0f8, raw[(i << 2) + 1]), # A # ! 在最前面
        ))
    end
    result
end

# %ignore-begin
let
    @show raw2argb!(copy(file_raw))
end
# %ignore-end

v = UInt8[0x01, 0x02, 0x03, 0x04, 0x05, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x04, 0x01, 0x02, 0x00, 0x02, 0x01, 0x02, 0x03, 0x01]
raw2argb!(copy(file_raw)) = ARGB{N0f8}[ARGB{N0f8}(0.125,0.329,0.408,0.137), ARGB{N0f8}(0.451,0.125,0.4,0.412), ARGB{N0f8}(0.424,0.396,0.125,0.412), ARGB{N0f8}(0.451,0.125,0.427,0.412), ARGB{N0f8}(0.388,0.408,0.412,0.38), ARGB{N0f8}(0.396,0.176,0.404,0.431), ARGB{N0f8}(0.431,0.396,0.447,0.396), ARGB{N0f8}(0.455,0.396,0.392,0.38), ARGB{N0f8}(0.176,0.125,0.396,0.125), ARGB{N0f8}(0.412,0.455,0.412,0.392), ARGB{N0f8}(0.404,0.125,0.412,0.431), ARGB{N0f8}(0.125,0.392,0.412,0.455), ARGB{N0f8}(0.396,0.388,0.455,0.447), ARGB{N0f8}(0.475,0.125,0.412,0.424), ARGB{N0f8}(0.125,0.431,0.435,0.451), ARGB{N0f8}(0.125,0.38,0.392,0.455), ARGB{N0f8}(0.412,0.451,0.396,0.463), ARGB{N0f8}(0.039,0.039,0.416,0.392), ARGB{N0f8}(0.424,0.412,0.38,0.459), ARGB{N0f8}(0.463,0.396,0.447,0.373), ARGB{N0f8}(0.412,0.435,0.431,0.451), ARGB{N0f8}(0.239,0.125,0.133,0.125), ARGB{N0f8}(0.18,0.192,0

像素序列⇒像素矩阵

In [102]:
"""
分解整数为「两个相近整数的乘积」
- 🎯根据像素序列计算最终图像尺寸
    - 原则：图像尽可能【方正】而非【扁长】
- 📌使用质因数分解，从开根往小处过滤
    - 第一个数 ≤ 第二个数
"""
function size_1to2(n::I)::Tuple{I,I} where {I <: Integer}
    # 首先开根
    local n1::I = I(floor(sqrt(n)))
    # 然后递减
    while !iszero(n % n1) && n1 > 0
        n1 -= 1
    end
    # 最后相除返回
    return (n1, n ÷ n1)
end

# %ignore-begin
let
    @assert @show(size_1to2(12)) == (3, 4)
    @assert @show(size_1to2(123)) == (3, 41)
    @assert @show(size_1to2(169)) == (13, 13)
end
# %ignore-end

"""
重整化「像素向量」
- 📌需要保留其中像素的类型
    - 只有类似`Matrix{ARGB{N0f8}}`的类型才能被save
"""
reshape_pixels(pixels::Vector{T}) where T = Matrix{T}(reshape(pixels, size_1to2(length(pixels))))

# %ignore-begin
let
    @show file_raw |> copy |> raw2argb! |> reshape_pixels
end
# %ignore-end

size_1to2(12) = (3, 4)
size_1to2(123) = (3, 41)
size_1to2(169) = (13, 13)
((file_raw |> copy) |> raw2argb!) |> reshape_pixels = ARGB{N0f8}[ARGB{N0f8}(0.125,0.329,0.408,0.137) ARGB{N0f8}(0.125,0.38,0.392,0.455) ARGB{N0f8}(0.447,0.435,0.416,0.439) ARGB{N0f8}(0.392,0.396,0.439,0.357) ARGB{N0f8}(0.125,0.133,0.392,0.239) ARGB{N0f8}(0.176,0.388,0.212,0.224) ARGB{N0f8}(0.384,0.451,0.455,0.255) ARGB{N0f8}(0.133,0.263,0.408,0.125) ARGB{N0f8}(0.18,0.255,0.384,0.451) ARGB{N0f8}(0.192,0.192,0.396,0.176) ARGB{N0f8}(0.212,0.208,0.388,0.176) ARGB{N0f8}(0.176,0.188,0.196,0.192) ARGB{N0f8}(0.208,0.384,0.392,0.208) ARGB{N0f8}(0.392,0.208,0.388,0.38) ARGB{N0f8}(0.208,0.4,0.192,0.176) ARGB{N0f8}(0.365,0.365,0.039,0.451) ARGB{N0f8}(0.384,0.216,0.4,0.396) ARGB{N0f8}(0.22,0.204,0.176,0.224) ARGB{N0f8}(0.396,0.388,0.455,0.337) ARGB{N0f8}(0.396,0.38,0.447,0.431) ARGB{N0f8}(0.396,0.176,0.451,0.396) ARGB{N0f8}(0.388,0.2,0.212,0.133) ARGB{N0f8}(0.125,0.125,0.357,0.125) ARGB{N0f8}(0.125,0.239,0.125,0.455) ARGB{N0f

15×109 Array{ARGB{N0f8},2} with eltype ARGB{N0f8}:
 ARGB{N0f8}(0.125,0.329,0.408,0.137)  …  ARGB{N0f8}(0.384,0.204,0.388,0.2)
 ARGB{N0f8}(0.451,0.125,0.4,0.412)       ARGB{N0f8}(0.208,0.176,0.224,0.212)
 ARGB{N0f8}(0.424,0.396,0.125,0.412)     ARGB{N0f8}(0.208,0.212,0.176,0.2)
 ARGB{N0f8}(0.451,0.125,0.427,0.412)     ARGB{N0f8}(0.22,0.196,0.216,0.208)
 ARGB{N0f8}(0.388,0.408,0.412,0.38)      ARGB{N0f8}(0.384,0.192,0.396,0.176)
 ARGB{N0f8}(0.396,0.176,0.404,0.431)  …  ARGB{N0f8}(0.176,0.22,0.388,0.38)
 ARGB{N0f8}(0.431,0.396,0.447,0.396)     ARGB{N0f8}(0.38,0.192,0.38,0.216)
 ARGB{N0f8}(0.455,0.396,0.392,0.38)      ARGB{N0f8}(0.204,0.208,0.188,0.22)
 ARGB{N0f8}(0.176,0.125,0.396,0.125)     ARGB{N0f8}(0.4,0.133,0.039,0.212)
 ARGB{N0f8}(0.412,0.455,0.412,0.392)     ARGB{N0f8}(0.396,0.447,0.451,0.463)
 ARGB{N0f8}(0.404,0.125,0.412,0.431)  …  ARGB{N0f8}(0.435,0.431,0.125,0.412)
 ARGB{N0f8}(0.125,0.392,0.412,0.455)     ARGB{N0f8}(0.125,0.133,0.192,0.239)
 ARGB{N0f8}(0.396,0.388,0.455,0.447) 

In [103]:
#= %only-compiled
export raw2png!, raw2png # * 导出核心函数
%only-compiled =#

"""
    raw2png(目标类型or目标路径, 待转换对象)
将文件转换为图片
- 📌主要流程：文件路径⇒字节串（向量）⇒像素矩阵（图像）|图片路径
"""
function raw2png end

# 文件⇒向量
raw2png(from::AbstractString) = raw2png("$from.png", from)
raw2png(destination, from::AbstractString) = raw2png(
    destination,
    from |> read
)

# 向量⇒矩阵
raw2png!(::Type{<:Vector}, raw::Vector{UInt8}) = raw # * 若指定输出格式为「向量」，则返回自身
raw2png!(destination, raw::Vector{UInt8}) = raw2png(
    destination,
    raw |> raw2argb! |> reshape_pixels
)
raw2png(destination, raw::Vector{UInt8}) = raw2png!(destination, copy(raw))

# 矩阵⇒自身|文件
raw2png(::Type{<:Matrix}, image::Matrix) = image # * 若指定输出格式为「矩阵」，则返回自身
raw2png(destination::AbstractString, image::Matrix) = PNGFiles.save(destination, image)

# %ignore-below # * 测试
let # * 纯测试图片
    raw2png("$file.test.png", file)
    raw2png(path) # ! 尝试把测试用图片再转换下
end
# 尝试自压缩自解压，以便自检
let SELF_PATH = "TWayFoil.ipynb"
    content = read(SELF_PATH, String)
    png = raw2png(Matrix, SELF_PATH)
    @show size(png)
    raw = png2raw(Vector, png)
    re_content = String(raw)
    if re_content != content
        write("err.re_content.test.txt", re_content)
        write("err.content.test.txt", content)
    end
    @assert re_content == content
end

size(png) = (10, 59669)


## 关闭模块上下文

In [104]:
#= %only-compiled
end # module
%only-compiled =#

## 尝试自编译

In [105]:
# %ignore-cell
SELF_NAME = "TWayFoil"
SELF_PATH_NOTEBOOK = "$SELF_NAME.ipynb"
SELF_PATH_JL = "$SELF_NAME.jl"
try
    using IpynbCompile: compile_notebook
    compile_notebook(SELF_PATH_NOTEBOOK, SELF_PATH_JL)
catch e
    showerror(e, stacktrace(Base.catch_backtrace()))
end

7266